name: Exercicio do módulo 3 do curso Github4Women

on:
  push: # Aciona quando há push 
  schedule:
    - cron: '0 * * * *'  # Executa a cada hora

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Rodar script ou comando
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x' 

      - name: Restaurar dependências
        run: dotnet restore **/*.csproj

      - name: Build do projeto
        run:  dotnet build **/*.csproj --no-restore